---
title: "Science Tracking Across the Project LifEspan"
format: 
  html:
    page-layout: full
---

Scientific research has become increasingly complex, requiring specialized skills, interdisciplinary work, and collaboration among large teams. Managing such projects and tracking data and metadata has become a significant challenge. The need for FAIR (findable, accessible, interoperable, and reusable) open data, materials, and metadata has similarly grown -- especially considering recent mandates for required sharing for federally funded projects. While user-friendly software tools that help researchers structure metadata exist, few researchers are aware of their necessity and usefulness---the onus is still on the project team to collect and curate this information. Studies using teams of researchers require sophisticated tracking of all project elements, and therefore, there is a need for scientific project management software that is tailored to the management of all manner of science projects. Software that promotes best practices in FAIR data and metadata would increase openness in all reporting, and tracking, and reporting standards.

Therefore, STAPLE was designed to be a science focused project management tool that not only helps with the unique challenges of project management of research but includes open and transparent documentation of data and metadata! We aim to have a global impact by promoting the transformation to open science and including researchers and their works that may be commonly ignored, regardless of technical capabilities, so that it is open to everyone. By creating software that allows a point and click interface with error feedback and automated validation, we hope to promote inclusivity within the scientific community by enabling everyone to participate in transparency and openness.

Check out our current progress at: <a href="https://staple.science/posts.html">the update blog</a>.

Check out and use the app at: <a href="https://app.staple.science/">the app</a>.

Learn more about who we are: <a href="https://staple.science/about.html">the about page</a>.
