---
title: "Privacy Policy"
format: 
  html:
    page-layout: full
---

## PRIVACY POLICY

STAPLE is open source software shared under a CC-BY-4.0 International Attribution license. This document covers the terms of use for our hosted version of the software at https://app.staple.science/. This privacy policy applies to those who add their content to our website.

In this document, we use "you" to refer to researchers and other users of our Websites and Services. We do not collect any personally identifiable information about you when you visit our Websites unless you choose to provide us with that information. We do not collect information from you for commercial marketing or any other purpose unrelated to our purpose.

Our goal is to provide you with a personalized online experience that provides you with the information, resources, and services that are most relevant and helpful to you. This Privacy Policy has been written to describe the conditions under which our Websites and Services are made available to you. Our Privacy Policy discusses, among other things, how data obtained during your visits to our Websites may be collected and used. Our Privacy Policy also discusses important limitations to the way you may use materials and services you find on the site. Read the Privacy Policy carefully. By providing affirmative consent, you have accepted the terms of this Policy. If you do not agree to accept the terms of the Privacy Policy, you are directed to discontinue accessing or otherwise using the site or any materials obtained from it.

We protect your personal information using industry-standard safeguards. As described in this Privacy Policy, we may share your information with your consent or as required by law as detailed in this policy, and we will let you know when we make changes to this Privacy Policy by posting changes to the site.

### 1. CONSENT

You are asked to provide explicit agreement to the terms of this Privacy Policy in order to use our Websites and Services, to deposit and/or publish your personal information on or through our Websites. Further, we obtain your consent before collecting any personal data. More information on specific privacy settings for Projects is provided in Section 11.

### 2. SITES COVERED BY THIS PRIVACY POLICY

This Privacy Policy applies to the STAPLE website located at app.staple.science. Our privacy practices are based on administrator and collaborator access to data.

### 3. CHANGES TO THIS PRIVACY POLICY

The process of maintaining a website is an evolving one, and STAPLE may modify and amend this Privacy Policy by posting a new Policy on our Websites. Please review any posted changes to our Privacy Policy carefully. If you agree to the terms, simply continue to use our Websites and Services. If you object to any of the changes to our Privacy Policy, please do not continue to access our Websites or use our Services, as your continued use of our Websites and Services after we have posted a notice of changes to the Privacy Policy shall constitute your consent to the changed terms or practices. Note that any personal data we collect about you is subject to the privacy policy in effect at the time of its collection. And, further, that you have certain rights with respect to that personal data, as described in this Privacy Policy.

### 4. CHILDREN'S PRIVACY

STAPLE is committed to protecting the privacy needs of children. STAPLE does not intentionally collect information from children under the age of 16, and STAPLE does not target its sites to children. Only persons who are more than 18 years-old or an emancipated minor may use our Websites and Services. By accessing our Websites and Services, you are legally acknowledging that you are over the age of 18 or an emancipated minor. If you are under the age of 18, you don't have the legal right to access our Websites and Services.

### 5. CALIFORNIA SHINE THE LIGHT LAW

California residents who provide personal information in obtaining products or services for personal, family or household use are entitled to request and obtain from us, once per calendar year, information about the customer information we shared, if any, with other businesses for their own direct marketing uses. If applicable, this information would include the categories of customer information and the names and addresses of those businesses with which we shared customer information for the immediately prior calendar year. To obtain this information, please email us at staple.helpdesk\@gmail.com with the subject line "Request for California Privacy Information", we will send you a reply e-mail containing the requested information. Not all information sharing is covered by the "Shine the Light" requirements and only information on covered sharing will be included in our response.

### 6. SECURITY

We have implemented industry-standard security safeguards designed to protect the personal information that you may provide. We also periodically monitor our system for possible vulnerabilities and attacks, consistent with industry standards. You should be aware, however, that since the Internet is not a 100% secure environment, we cannot ensure or warrant the security of any information that you submit to the site. There's also no guarantee that information may not be accessed, disclosed, altered, or destroyed by breach of any of our physical, technical, or managerial safeguards. It's your responsibility to protect the security and integrity of your account details, including your username and password. To maintain the security of your information (or another user's personal information that you are authorized to manage as an Administrator), you must keep your username(s) and password(s) strictly confidential and not disclose them to anyone. You will be solely responsible for any action, activities, and access to our Websites and Services that are taken using your username and password and that occurred before you notified us of their loss.

### 7. TYPES OF INFORMATION WE COLLECT

(a) Registration

Unless you are a member of the general public with limited viewing rights, in order to fully use the STAPLE Websites and Services, you will need to create an account by providing us with at least your name, email address, and a password. You can choose to provide other information about yourself in your account profile during the registration process (for example, your organizational or company affiliation, your level of education, location, your job title, professional experience, professional affiliations and memberships, etc.). This information that you voluntarily provide may be seen by other users who view your profile. We collect this information only with your consent.

We use this additional information to customize your experience on this website, and this information may be viewable by others. You understand that, by creating or claiming an account, STAPLE and others within your project's collaboration will be able to identify you by your profile. Within a project, project managers may request personal information based on their project needs such as name, affiliation, e-mail address, and/or funding information. You are not required to provide this information to use STAPLE, but should be aware it may be shared outside of STAPLE as part of project metadata.

(b) Non-Personal Information

Non-personal information is data about usage and service operation that is not directly associated with a specific personal identity STAPLE may collect, analyze, and share aggregated non-personal information to evaluate how visitors use our Websites and Services.

(c) Aggregate Information

STAPLE may collect aggregate information, which refers to information your computer automatically provides us and that cannot be tied back to you as a specific individual. This information can be shared with third parties without restriction. Examples include referral data (the sites you visited just before and just after our site), the pages viewed, the date of your visit, and time spent at our Websites.

(d) Log Files and IP Addresses

We may collect information from the devices and networks that you use to visit the Websites in order to help improve the services we provide, including your Internet Protocol Address (IP Address). An IP address is a number that is automatically assigned to your computer whenever you access the Internet. For example, when you request a page from one of our sites, our servers log your IP address to create aggregate reports on user demographics, traffic patterns, metascience, and for purposes of system administration. Every time you request or download a file from the site, STAPLE may store data about these events and your IP address in a log file. We may use this information to analyze trends, administer the site, track users' movements, and gather broad demographic information for aggregate use or for other business purposes. When you access or leave our Websites by clicking on a hyperlink, we receive the URL from the site from which you last visited or the one to which you're directed. We may receive the Internet Protocol ("IP") address of your computer or proxy server used to access the site, your operating system, the type of browser you used, and the type of device you use, the Application Programming Interface ("API") you use, or your mobile device carrier or your ISP. We also may receive location data passed to us from third-party services or GPS-enabled devices that you have set up in order to customize your experience based on location information.

(e) Cookies

We use cookies and similar technologies, including mobile device identifiers, to help us recognize you when you log into our Websites and Services. By accessing our Websites, you are consenting to the placement of cookies and other similar technologies in your browser in accordance with this Privacy Policy and our Terms of Use.

Cookies are small packets of information that a site's computer stores on your computer. STAPLE can then read the cookies whenever you visit our Websites. We may use cookies in a number of ways, such as to save the fact that you are logged into the system so you don't have to relogin each time you visit our Websites, to deliver content specific to your interests, and to track the pages you've visited. These cookies allow us to use the information we collect to customize your experience so that your visit to our Websites and your use of our Services are as relevant and as valuable to you as possible. You may modify and control how and when cookies are set through your browser settings. Most browsers offer instructions on how to reset the browser to control or reject cookies in the "Help" section of the toolbar. We do not link non-personal information from cookies to personally identifiable information without your permission.

(f) New Technologies

As new technologies emerge, STAPLE may be able to improve our services or provide you with new ones, which means that STAPLE may create new ways to collect information on our Websites. If we offer a new service or new features to our existing Websites, for example, these changes may result in our collecting new information in order to improve your user experience.

### 8. STAPLE ADMINISTRATORS AND MODERATORS

If you contact STAPLE, we collect information that helps us categorize your question or report, respond to it, and, if applicable, investigate any breach of our Terms of Use or this Privacy Policy. We also may use this information to track potential problems and trends in order to improve our services to you and to the community as a whole.

### 9. LINKS TO THIRD-PARTY SITES AND SERVICES

Our Websites and Services may provide links to third-party sites for the convenience of our users. If you access those links or third-party add-ons, you will leave our Websites or use the services of another Website. STAPLE does not control these third-party sites and cannot represent that their policies and practices will be consistent with this Privacy Policy or our Terms of Use. For example, other sites may collect or use personal information about you in a manner different from that described in this document. You should be aware that materials available through third-party sites may be protected from unauthorized copying and dissemination by U.S. copyright law, trademark law, international conventions, and other intellectual property laws, and the usage of such materials may be subject to limitations that are more or less restrictive than those expressed herein. Therefore, you should use other sites with caution, and you do so at your own risk. We encourage you to review the privacy policy of any site before submitting personal information.

We may receive information when you use your account to log into a third-party site or application in order to recommend tailored information to you and to improve your user experience on our Websites. We may provide reports containing aggregated impression information to third parties to measure Internet traffic and usage patterns.

### 10. DEFINITIONS

**Content.** As used in these Terms of Use, "content" means, but is not limited to, information you add to STAPLE.

**Users.** All Users must accept the STAPLE Terms of Use and Privacy Policy.

**Project Manager**. An individual who has the power to create, add, edit, and update all parts of project tracking and metadata.

**Contributor**. An individual who has the power to enter information for a project, but cannot view or edit all parts of a project.

### 11. PRIVACY SETTINGS

Projects can be created by a project manager. If a project manager wishes to send you an invitation to participate in a project STAPLE will send you a notification. Once you accept the invitation, your information may be made available to others collaborating project subject to the specific privacy access restrictions imposed by the project manager of your project.

If the output metadata from STAPLE is shared publicly, there is no way for STAPLE to restrict people who have previously viewed or downloaded the previously publicly accessible content from using it.

### 12. HOW WE USE YOUR PERSONAL INFORMATION

When you register with STAPLE, you acknowledge that information you provide on your membership profile may be seen by others and used by STAPLE as described in this Privacy Policy and our Terms of Use.

(a) Consent to STAPLE to Use Personal Information

STAPLE may use personal information you supply to provide services that support the activities of the organization, its members, and their collaboration on Projects: contacting users, understanding aggregate usage of the site, and tailoring services. When accessing the Websites, your personal user information may be tracked by STAPLE in order to support collaboration, ensure authorized access, and enable communication between collaborators.

The personal information you may provide to STAPLE may reveal or allow others to discern aspects of your life that are not expressly stated in your profile (for example, your picture or your name may reveal your gender). By consenting to provide personal information to us when you create or update your account and profile, you accept and agree to our processing of your personal information in ways set out by this Privacy Policy. Supplying information to us, including any information deemed "sensitive" by applicable law, is entirely voluntary on your part. You may withdraw your consent to STAPLE's collection and processing of your information by changing or closing your account, as more fully described in this Privacy Policy.

(b) Communications from STAPLE

We use the information you provide to customize your experience on the site. We may communicate with you using email or other means available to us regarding the availability of services, service-related issues, or announcements that we believe may be of interest to you. We may, for example, send you welcome messages and emails regarding new features or services, and promotional information from STAPLE. You may opt out of receiving promotional messages from STAPLE by following the instructions contained in the email. As long as you're a registered user, however, you can't opt out of receiving service messages from us. STAPLE may also use personal information in order to customize content on the site to you, such as news relevant to you or to your industry or company.

(c) Communications from Others

Personal contact information may be provided to other members of a Project on a secure site to encourage and facilitate collaboration, research, and the free exchange of information. Please remember that any information (including personal information) that you disclose on the public sections of our Websites, such as forums, message boards, and news groups, becomes public information that others may collect, circulate, and use. Because we cannot and do not control the acts of others, you should exercise caution when deciding to disclose information about yourself or others in public forums such as these.

(d) Sharing Information with Third Parties

Information you put on your profile may be seen by others. Information collected as part of a project may be shared outside of STAPLE. You are responsible for any information you post on our Websites, and, subject to our Terms of Use and Privacy Policy, this information may be accessible to others. Accordingly, you should be aware that any information you choose to disclose on our Websites or Services may be read, collected, and used by other users within STAPLE. STAPLE is not responsible for the information you choose to submit on our Websites.

STAPLE does not rent or sell or otherwise distribute personal information that you have shared with us, except as permitted in this Privacy Policy and our Terms of Use. We will not disclose personal information that is associated with your profile unless STAPLE has a good-faith belief that disclosure is permitted by law or is reasonably necessary to: (1) comply with a legal requirement or process, including, but not limited to, civil and criminal subpoenas, court orders or other compulsory disclosures; (2) investigate and enforce this Privacy Policy or our Terms of Use; (3) respond to claims of a violation of the rights of third parties; (4) respond to member service inquiries; (5) protect the rights, property, or safety of STAPLE, our users, or the public; or (6) as part of the sale of the assets of STAPLE or as a change in control of the organization or one of its affiliates or in preparation for any of these events. STAPLE reserves the right to supply any such information to any organization into which STAPLE may merge in the future or to which it may make any transfer in order to enable a third party to continue part or all of the organization's mission. Any third party to which STAPLE transfers or sells its assets will have the right to use the personal and other information that you provide in the manner set out in this Privacy Policy.

### 13. DATA TRANSFER

STAPLE may store and process personal information on servers or on a cloud located outside of the country where you originally deposited data. The data-protection laws of the country or countries where this personal information will be stored or processed might not be as comprehensive as those in your country. If you are unsure whether this Privacy Policy is in conflict with applicable local rules, you should not submit your information. If you are located within the European Union, you should note that your information will be transferred to the United States, which is deemed by the European Union to have inadequate data protection. By using our Websites and/or directly providing personal information to us, you hereby agree to and acknowledge your understanding of the terms of this Privacy Policy, and consent to have your personal data transferred to and processed in the United States and/or in other jurisdictions as determined by STAPLE, notwithstanding your country of origin, or country, state, and/or province of residence.

### 14. GOVERNING LAW

This Privacy Policy is governed in all respects by the laws of the state of Louisiana, excluding that state's conflicts of laws provisions.

### 15. YOUR OPT-OUT OPTIONS

You may access, modify, correct, or delete your personal information controlled by STAPLE regarding your profile, and you may close your account. You can also contact us for any account information which is not on your profile or readily accessible to you. If you close your account, some or all of your profile information may continue to remain visible on the Websites.

You should be aware that information that you've shared with others or that others have copied may also remain visible after you have closed your account or deleted the information from your own profile. In addition, you may not be able to access, correct, or eliminate any information about you that other users have copied or exported out of the Websites, because this information may not be in our organization's control. Your public profile may be displayed in search engine results.

From time to time STAPLE may email you electronic newsletters, announcements, surveys, or other information unrelated to any Project. If you prefer not to receive any or all of these communications, you may opt out by following the directions provided within the electronic newsletters and announcements. STAPLE also may conduct polls and surveys of our users, and your participation in this type of research is at your sole discretion. STAPLE may follow up with you regarding your participation in this research. You may at any time opt out of participating in these polls and surveys.

Further, STAPLE may send you occasional Service-related emails that you may not opt-out of (e.g. changes or updates to features of our Services that have security or privacy implications, technical and security notices, account verification).

### 16. DATA RETENTION

We will keep your personal information for as long as your account is active or as needed to comply with our legal obligations, even after you've closed your account, such as to meet regulatory requirements, resolve disputes between users, to prevent fraud and abuse, or to enforce this Privacy Policy and our Terms of Use. We may be required to retain personal information for a limited period of time if requested by law enforcement. We also may retain indefinitely non-personally identifiable, aggregate data to facilitate our ongoing operations.

### 17. GENERAL DATA PROTECTION REGULATION

If you are a resident of or are located in the European Economic Area (“EEA”), you may have certain rights under the General Data Protection Regulation (“GDPR”). Personal data you provide is only collected with your consent, and may be transmitted outside of the EEA to STAPLE (or computer servers maintained for the benefit of STAPLE) pursuant to that consent.

In general, under the GDPR you may: + request access to your personal data + have incomplete or incorrect data corrected + have your personal data deleted + suspend or restrict our use of your personal data, or withdraw your consent + request a copy of your personal data + complain to a supervisory authority if you believe your rights under the GDPR are not being respected

Should you request a copy of your personal data, we will supply to you a copy of your personal data. The first copy will be provided free of charge, but additional copies may be subject to a reasonable fee. Should you request the deletion of your personal data, STAPLE will generally do so as soon as practicable, although your right to have your personal data deleted is subject to exceptions, such as, for example, compliance with a legal obligation or for the establishment, exercise or defense of legal claims.

If you consider that our processing of your personal information infringes data-protection laws, you have a legal right to lodge a complaint with a supervisory authority responsible for data protection. You may do so in the EU member state of your habitual residence, your place of work or the place of the alleged infringement.

Contact STAPLE at staple.helpdesk\@gmail.com if you have concerns regarding your personal data, or wish to exercise any of these listed rights.

Note that, if you are in the EEA, we may transfer your personal data outside of the EEA, including to the United States. By way of example, this may happen if your personal data is transferred to our servers located in a country outside of the EEA. These countries may not have similar data-protection laws to the EEA. By submitting your personal data, you’re agreeing to this transfer, storing, or processing. If we transfer your information outside of the EEA in this way, we will take steps to ensure that appropriate security measures are taken with the aim of ensuring that your privacy rights continue to be protected as outlined in this policy.

Adapted from the Center for Open Science: [Privacy Policy](https://github.com/CenterForOpenScience/cos.io/blob/master/PRIVACY_POLICY.md)
