---
title: "Terms and Conditions"
format: 
  html:
    page-layout: full
---

## TERMS AND CONDITIONS OF USE

### 1. INTRODUCTION

STAPLE is open source software shared under a CC-BY-4.0 International Attribution license. This document covers the terms of use for our hosted version of the software at https://app.staple.science/. These terms of service apply to those who add their content to our website.

These Terms of Use describe the conditions under which the STAPLE allows the public to use the Websites and Services.

### 2. TERMS OF USE

In order to use the Websites and Services made available on the sites, whether by accessing our Websites directly or by using a public application programming interface ("Public API") to access our Websites and Services, you must first agree to these Terms of Use. You may not use the Websites or Services if you do not accept these terms. You can accept these terms by clicking to accept or agree to these terms where we have provided you with clickable electronic assent option or by actually using the services offered at the Websites. If you are using the Websites or Services on behalf of a business or organization, your assent to these terms constitutes a binding legal agreement that that business or organization for which you're acting as a representative accepts these terms, to the extent authorized by law. Any such business or organization will hold harmless and indemnify the STAPLE, and its agents and representatives, and its and their directors, officers, and employees from and against any liability, damage, loss, cost, or expense (including, without limitation, reasonable attorneys' fees) arising from or relating to its and your use of the Websites and Services, including data or software deposited by you or it, or in violation of these Terms of Use. You understand and agree that we will treat your use of the Websites and Services offered thereon as acceptance of these terms.

Our Privacy Policy, which is incorporated by reference into these Terms of Use, explains how we treat your personal data and your privacy when you use our Websites and Services. By using our Websites and Services, you agree that the STAPLE can use such data in accordance with our Privacy Policy.

### 3. MODIFICATIONS TO THESE TERMS OF USE

We may modify these Terms of Use from time to time by posting a revised version on our Websites and/or Services. Your continued use of the Websites or Services after the posting of such new Terms of Use means that you agree to the posted changes. If you do not agree to the changes, you should discontinue use of the Websites and Services. If there is a conflict between these Terms of Use and the updated and/or additional terms and conditions, the updated and/or additional terms and conditions will control.

If you have questions about our Websites and Services, please contact us by email at staple.helpdesk\@gmail.com.

### 4. DEFINITIONS

**Content.** As used in these Terms of Use, "content" means, but is not limited to, information you add to STAPLE.

**Users.** All Users must accept the STAPLE Terms of Use and Privacy Policy.

**Project Manager**. An individual who has the power to create, add, edit, and update all parts of project tracking and metadata.

**Contributor**. An individual who has the power to enter information for a project, but cannot view or edit all parts of a project.

### 5. YOUR RIGHT TO USE STAPLE

The Websites contain technology that is owned by the STAPLE. The code behind STAPLE is available on an open-source basis. The STAPLE grants you a limited license to make use of the STAPLE software our hosted version.

### 6. PRIVACY SETTINGS RESTRICTING ACCESS TO CONTENT

The STAPLE supports open access to information in the research community. The STAPLE shares with the public free of charge any data marked as Public through its Websites and Services for viewing and use unless otherwise noted. All information you enter on our website is restricted to users who are provided access via project collaboration. You own all content entered into STAPLE. Your content will be viewable in the following ways:

**Administrators**: Individuals marked as project managers can see all content entered on projects they administer.

**Contributors**: Contributors can only see their content entered on projects in which they are a collaborator.

**Teams**: Team members can see content entered by any member of a team only for team specific tasks.

### 7. YOUR REPRESENTATIONS AND WARRANTIES

You represent and warrant to the STAPLE that: a. If you enter information on STAPLE, you are authorized to do so with the STAPLE and that you have the authority to bind the business or organization that you represent to these Terms of Use and our Privacy Policy. b. If you are a project manager, you are not misrepresenting your identity or organizational affiliations in any manner. c. If you are a registered user, you will update and maintain the accuracy of your contact information.

### 8. AUDIT TRAILS

To ensure the transparency of the STAPLE and as a feature of STAPLE, we may, but are not required to, keep an audit trail log when and by whom data or information has been deposited or changed and any changes to a Project's privacy settings. While the STAPLE requires all data deposited be accurate, the STAPLE takes no responsibility for the accuracy of the data on the Websites or the Services. Each party agrees to hold the the other party and its representatives and agents, and its and their directors, officers and employees harmless regarding any disputes regarding data deposits and privacy settings and any claims, regardless of theory of law, arising from such disputes.

### 9. PERMITTED AND PROHIBITED USES

The STAPLE operates open services developed by and for the research community. We encourage you to consider community norms and expectations in your use of the Websites and Services.

You may not use the Websites or Services to violate any applicable local, state, national, or international law, including without limitation any applicable laws relating to antitrust or other illegal trade or business practices, federal and state securities laws, regulations promulgated by the U.S. Securities and Exchange Commission, any rules of any national or other securities exchange, and any U.S. laws, rules, and regulations governing the export and re-export of commodities or technical data. You may not upload or transmit any data, content, or material that infringes or misappropriates any person's copyright, patent, trademark, or trade secret, or disclose via the Websites or Services any information the disclosure of which would constitute a violation of any confidentiality obligation on your part. You may not upload any viruses, worms, Trojan horses, or other forms of harmful computer code, nor subject the STAPLE's networks or servers to unreasonable traffic loads, or otherwise engage in conduct deemed disruptive to the ordinary operation of the STAPLE's Websites and Services. You're strictly prohibited from communicating on or through this site any unlawful, harmful, offensive, threatening, abusive, libelous, harassing, defamatory, vulgar, obscene, profane, hateful, fraudulent, sexually explicit, racially, ethnically, or otherwise objectionable material of any sort, including, but not limited to, any material that encourages conduct that would constitute a criminal offense, give rise to civil liability, or otherwise violate any applicable local, state, national, or international law. You are further prohibited from harvesting addresses, email addresses, or other personal data for commercial purposes and from sending unsolicited or unauthorized advertising, promotional materials, or other unsolicited communications to other users of the Websites or Services. You may not use the Websites or Services in a way that harms the STAPLE or the STAPLE's members, affiliates or vendors, or other users. You may not deposit, edit, modify, or otherwise use any data in a manner that makes it false, incomplete or misleading, except to anonymize or protect identifying information as required by ethical or legal prescriptions for sharing data. You may not manipulate identifiers to disguise the origin of any data. You may not use STAPLE or the STAPLE marks in any way to suggest an affiliation with or endorsement by the STAPLE of any individual, organization, product, service, or research.

You acknowledge that your unauthorized use or misuse of the Websites and Services could cause the STAPLE irreparable harm. Any unauthorized use of the Websites or Services or other breach of these Terms of Use shall automatically terminate the license granted to you by the STAPLE. In addition, the STAPLE reserves the right, but is not obligated to, investigate any potential violations of its Terms of Use and/or any behavior that is potentially unlawful, and such investigations may involve cooperation with law enforcement authorities.

### 10. LIMITATION OF ACCESS AND REMOVAL OF CONTENT

The STAPLE makes commercially reasonable efforts to maintain and provide access to its Websites and Services and will endeavor to provide you with advance warning of restrictions to access due to routine website maintenance. The STAPLE, at its sole discretion, however, reserves the right at any time and from time to time to modify, suspend, discontinue, or terminate the Websites or Services or portions thereof with or without notice. You agree that we will not be liable to you or to any third party for any modification, suspension, discontinuation, or termination of the Websites or Services. While the STAPLE will endeavor to continue to host all Projects, as a non-profit entity, it cannot guarantee that it will have the resources to do so over time, and it reserves the right to designate a substitute host of its choosing for Project content if the STAPLE does not have the financial means to do so itself in the future.

The STAPLE is not responsible for screening or reviewing content submitted to the Websites or Services. The STAPLE may temporarily or permanently remove any content on the Websites or Services at any time where the STAPLE, in its sole discretion believes the content is in violation of these Terms of Service or where the STAPLE is acting in compliance with the Digital Millennium Copyright Act. You are advised not to use the Websites or Services as the exclusive storage repository for your data and content. The STAPLE recommends that you separately store all data and content submitted to the Websites and Services on other secure servers or with reputable third-party hosting services.

### 11. SECURITY

The STAPLE uses commercially reasonable, industry-standard measures to protect the security of the STAPLE's Websites and its Services. Despite these measures, we cannot guarantee that unauthorized persons will not be able to defeat our security measures. Your access to some of our Websites and Services and content may be password-protected. To maintain the security of your information (or another user's personal information that you are authorized to manage as an Administrator), you must keep your username(s) and password(s) strictly confidential and not disclose them to anyone. You will be solely responsible for any action, activities, and access to our Websites and Services that are taken using your username and password and that occurred before you notified us of their loss. If you become aware of any security breach of your password or of the security of the Websites or Services, you must contact us as soon as possible.

### 12. LINKS AND ADD-ONS

The Websites and Services may contain links or allow you to make use of Add-ons that connect to sites owned or operated by independent third parties. These links are provided for your convenience and reference only. The STAPLE's Terms of Use and Privacy Policy do not apply to those sites. We do not control such sites and, therefore, we are not responsible for any content posted on these sites or their privacy policies. The fact that the STAPLE offers such links should not be construed in any way as an endorsement, authorization, or sponsorship of that site, its content or the companies or products or services referenced therein, and the STAPLE reserves the right to note its lack of affiliation, sponsorship, or endorsement of these sites. If you decide to access any of the third-party sites linked to the STAPLE's Websites or Services, you do this entirely at your own risk. Because some sites employ automated search results or otherwise link you to sites containing information that may be deemed inappropriate or offensive, the STAPLE cannot be held responsible for the accuracy, copyright compliance, legality, or decency of material contained in third-party sites or any results that may be obtained from using them. You hereby irrevocably waive any claim against us with respect to such sites.

### 13. INDEMNIFICATION

To the extent authorized by law, each party agrees to defend, indemnify, and hold harmless the other party, its employees, directors, officers, affiliated companies, agents, vendors, or suppliers from and against any and all claims, damages, costs, and expenses, including reasonable attorneys' fees, that are incurred in connection with any third-party claim arising from or related to your use or misuse of the Websites and Services, including, without limitation, your use of any Public API or third-party products accessing the Websites or Services via a Public API, your violation of these Terms of Use, or your infringement or that of any other user of your account, of any intellectual property right or other right of any person or entity.

### 14. TERMINATION

These Terms of Use are effective until terminated by either party. If you no longer agree to be bound by these Terms, you must cease use of the Websites and Services. If you're dissatisfied with the Websites, their content, our Services or any of these terms, conditions, and policies, your sole legal remedy is to discontinue using the Websites and Services. The STAPLE reserves the right to terminate or suspend your access to and use of the Websites and Services, or parts of the Websites and Services, without notice, if we believe, in our sole discretion, that such use is (i) in violation of any applicable law; (ii) is harmful to our interests or the interests, including intellectual property or other rights, of another person or entity; or (iii) where the STAPLE has reason to believe that you are in violation of these Terms of Use. Termination for any reason shall not terminate any of your warranties or any of your indemnification and other obligations under these Terms of Use, or any licenses that you have or other rights that you may have granted in connection with any of your contributions.

### 15. WARRANTY DISCLAIMER

NOTWITHSTANDING ANY OTHER PROVISION HERIN TO THE CONTRARY TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW: (1) THE WEBSITES AND SERVICES ARE PROVIDED ON AN "**AS IS**" AND "**AS AVAILABLE**" BASIS, AND (2) THE STAPLE DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT OF INTELLECTUAL PROPERTY. THE STAPLE MAKES NO REPRESENTATIONS OR WARRANTY THAT THE WEBSITES OR SERVICES WILL MEET YOUR REQUIREMENTS, OR THAT YOUR USE OF THE WEBSITES OR SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR FREE; NOR DOES THE STAPLE MAKE ANY REPRESENTATION OR WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE WEBSITES OR SERVICES. THE STAPLE MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THE WEBSITES OR SERVICES OR THE INFORMATION, CONTENT, DATA, MATERIALS, OR PRODUCTS DISPLAYED ON THE WEBSITES OR THE SERVICES.

NOTWITHSTANDING ANY OTHER PROVISION HERIN TO THE CONTRARY AND TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW: IN NO EVENT SHALL THE STAPLE OR ANY OF ITS AFFILIATED COMPANIES, EMPLOYEES, DIRECTORS, OFFICERS, AGENTS, VENDORS, OR SUPPLIERS BE LIABLE FOR ANY DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, BUSINESS INTERRUPTION, LOSS OF INFORMATION) ARISING OUT OF THE USE, MISUSE OF OR INABILITY TO USE THE WEBSITES OR SERVICES, EVEN IF THE STAPLE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THIS DISCLAIMER CONSTITUTES AN ESSENTIAL PART OF THESE TERMS. BECAUSE SOME JURISDICTIONS PROHIBIT THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. YOU UNDERSTAND AND AGREE THAT ANY DATA, CONTENT, OR SOFTWARE DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE WEBSITES, SERVICES, OR APPLICATION PROGRAMMING INTERFACES OR ANY THIRD-PARTY PRODUCT ACCESSING THE WEBSITES AND SERVICES IS AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM(S) OR LOSS OF DATA OR BUSINESS INTERRUPTION THAT RESULTS FROM THE DOWNLOAD OF DATA, CONTENT, OR SERVICES. THE STAPLE SHALL NOT BE RESPONSIBLE FOR ANY LOSS OR DAMAGE CAUSED, OR ALLEGED TO HAVE BEEN CAUSED, DIRECTLY OR INDIRECTLY, BY THE INFORMATION OR IDEAS OR RESEARCH CONTAINED, SUGGESTED OR REFERENCED IN OR APPEARING ON THE WEBSITES. YOUR USE AND PARTICIPATION IN THE WEBSITES AND SERVICES IS SOLELY AT YOUR OWN RISK. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM THE STAPLE OR THROUGH THE STAPLE, ITS EMPLOYEES, OR THIRD PARTIES SHALL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN. YOU ACKNOWLEDGE, BY YOUR USE OF THE WEBSITES AND SERVICES, THAT YOUR USE OF THE WEBSITES AND SERVICES IS AT YOUR SOLE RISK.

### 16. LIABILITY LIMITATION

NOTWITHSTANDING ANY OTHER PROVISION HERIN TO THE CONTRARY AND TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW: UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL OR EQUITABLE THEORY, WHETHER IN TORT, CONTRACT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE, SHALL THE STAPLE OR ANY OF ITS AFFILIATED COMPANIES, EMPLOYEES, DIRECTORS, OFFICERS, AGENTS, VENDORS, OR SUPPLIERS BE LIABLE TO YOU OR TO ANY OTHER PERSON FOR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL LOSSES OR DAMAGES OF ANY NATURE ARISING OUT OF OR IN CONNECTION WITH THE USE OF OR INABILITY TO USE THE WEBSITES OR SERVICES OR FOR ANY BREACH OF SECURITY ASSOCIATED WITH THE TRANSMISSION OF SENSITIVE INFORMATION THROUGH THE WEBSITES OR SERVICES OR FOR ANY INFORMATION OBTAINED THROUGH THE WEBSITES OR SERVICES, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOST PROFITS, LOSS OF GOODWILL, LOSS OR CORRUPTION OF DATA, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION, EVEN IF AN AUTHORIZED REPRESENTATIVE OF THE STAPLE HAS BEEN ADVISED OF OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES.

THE STAPLE'S TOTAL CUMULATIVE LIABILITY FOR ANY AND ALL CLAIMS IN CONNECTION WITH THE WEBSITE OR THE SERVICES WILL NOT EXCEED ONE THOUSAND U.S. DOLLARS (\$1,000.00). YOU AGREE AND ACKNOWLEDGE THAT THE FOREGOING LIMITATIONS ON LIABILITY ARE AN ESSENTIAL BASIS OF THE BARGAIN AND THAT THE STAPLE WOULD NOT PROVIDE THE WEBSITES OR SERVICES ABSENT SUCH LIMITATION.

### 17. USE OF SOFTWARE

If you download code or software tools (the "Software") from the Websites or Services, the use of the Software is subject to the license terms in the Software License Agreement that accompanies or is provided with the Software. If a Software License Agreement does not accompany or is not provided with the Software and the Software is sample or beta code or is provided for evaluation purposes, then you must contact the Project Administrator for the applicable Software License Agreement. You may not download or install the Software until you have read and accepted the terms of the applicable Software License Agreement.

### 18. TRADEMARKS

All other trademarks, registered trademarks, product names and company names or logos mentioned on the Websites and Services are the property of their respective owners. Reference to any product vendors, service providers, laboratories, auditors, products, services, processes, or other information, whether by trade name, trademark, manufacturer, supplier or otherwise, does not constitute or imply endorsement, sponsorship, or recommendation thereof.

### 19. ASSIGNMENT

Users may not assign or otherwise transfer the rights or obligations hereunder without the prior written consent of the STAPLE, which assignment will not be unreasonably refused. Any purported transfer without the STAPLE's written authorization shall be void. The STAPLE reserves the right to transfer all of its rights and obligations under these Terms of Use and Privacy Policy, including ownership and/or operation of the STAPLE to another non-profit entity continuing the STAPLE's purpose, in the event of a merger, joint venture, dissolution, or other organizational change. In no event shall the STAPLE's merger with or assignment of rights and obligations to a successor entity that carries on the STAPLE's purpose constitute a material breach or cessation of operations under these Terms.

### 20. GENERAL

The STAPLE is based in the United States. The STAPLE makes no claims that the data or content on its Websites or Services is appropriate or may be downloaded outside of the United States. Access to the Websites and Services may not be legal by certain persons or in certain countries. If you access the Websites from outside the United States, you do so at your own risk and are responsible for compliance with the laws of your jurisdiction. These Terms are governed in all respects by the laws of the the State of Louisiana, excluding that state's conflicts of laws provisions.

If you are a resident of or are located in the European Union or European Economic Area (“EEA”), you may also have certain rights under the General Data Protection Regulation (“GDPR”). Personal information (“Personal Data”) you provide is only collected with your consent, and is subject to the terms of the STAPLE Privacy Policy.

### 21. RESERVATIONS OF RIGHTS

All rights not explicitly granted herein are reserved.

Adapted from the Center for Open Science: (Terms and Conditions)\[https://github.com/CenterForOpenScience/cos.io/blob/master/TERMS_OF_USE.md?plain=1\]
